# 48962090
# 255233Ahmed@@

GET https://au-api.basiq.io/users/8a797336-3c77-4680-8e39-5dd920ac26e8/transactions?filter=transaction.postDate.gteq('2028-01-28')
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXJ0bmVyaWQiOiIzZWE4NTQzMS00OTNhLTQ4MTYtOTFkYS1hMjA5NGFlMDM3NTgiLCJhcHBsaWNhdGlvbmlkIjoiMWRhNjRkYjItMjk1Yi00ZmVlLWI2ZDQtZmM1MjE5NjdiZDUxIiwiYXBwbGljYXRpb25fdHlwZSI6IlJlZ3VsYXIiLCJzY29wZSI6IlNFUlZFUl9BQ0NFU1MiLCJzYW5kYm94X2FjY291bnQiOnRydWUsImNvbm5lY3Rfc3RhdGVtZW50cyI6ZmFsc2UsImVucmljaCI6ImRpc2FibGVkIiwiZW5yaWNoX2FwaV9rZXkiOiJWeU9VTkZjNnJvMzJqYllUbFVNY0gyd001ZDBLZFlYRDE3R09RZUZYIiwiZW5yaWNoX2VudGl0eSI6ZmFsc2UsImVucmljaF9sb2NhdGlvbiI6ZmFsc2UsImVucmljaF9jYXRlZ29yeSI6ZmFsc2UsImFmZm9yZGFiaWxpdHkiOiJzYW5kYm94IiwiaW5jb21lIjoic2FuZGJveCIsImV4cGVuc2VzIjoic2FuZGJveCIsImV4cCI6MTc2NDk4NTE3OCwiaWF0IjoxNzY0OTgxNTc4LCJ2ZXJzaW9uIjoiMy4wIiwiZGVuaWVkX3Blcm1pc3Npb25zIjpbXX0.UZAlMTQFQLU2zc5wkUq1bAHNPoVz3Xk8OUotG_v1M_Y


###
POST https://au-api.basiq.io/token
Authorization: Basic MWRhNjRkYjItMjk1Yi00ZmVlLWI2ZDQtZmM1MjE5NjdiZDUxOjI4MDg5Yzk1LTFhZDQtNDNjZi1hOTE3LTBhY2QxMWYyMWU3ZQ==
basiq-version: 3.0