/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FinancialAccountBankSyncers = "westpac";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type LoanType = "borrowed" | "lent";

export type ReconciliationGroup =
  | "budget"
  | "gst_payable"
  | "loan"
  | "project"
  | "refund"
  | "refunded"
  | "tax"
  | "unclassified";

export type ReconciliationProjectStream =
  | "labors"
  | "misc"
  | "payments"
  | "supplies";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

/**
 * Calendar dates (Postgres `date`) are represented as plain `YYYY-MM-DD`
 * strings with no timezone. See `src/lib/date.ts` and the type-1082 parser in
 * `src/db/index.ts`.
 */
export type CalendarDate = ColumnType<string, string, string>;

export interface _PrismaMigrations {
  appliedStepsCount: Generated<number>;
  checksum: string;
  finishedAt: Timestamp | null;
  id: string;
  logs: string | null;
  migrationName: string;
  rolledBackAt: Timestamp | null;
  startedAt: Generated<Timestamp>;
}

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface BudgetCategories {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  includingGst: boolean;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface BudgetCategoryAllocations {
  amount: number;
  budgetCategoryId: string;
  createdAt: Generated<Timestamp>;
  effectiveDate: CalendarDate;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface DrizzleDrizzleMigrations {
  createdAt: Int8 | null;
  hash: string;
  id: Generated<number>;
}

export interface FinancialAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  syncWithBank: FinancialAccountBankSyncers | null;
  updatedAt: Generated<Timestamp>;
}

export interface GstPayments {
  amount: number;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  periodFrom: CalendarDate;
  periodTo: CalendarDate;
  rate: number;
  reconciliationId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface LoanPayoffs {
  amount: number;
  createdAt: Generated<Timestamp>;
  date: CalendarDate;
  id: Generated<string>;
  loanId: string;
  notes: string | null;
  reconciliationId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Loans {
  amount: number;
  createdAt: Generated<Timestamp>;
  date: CalendarDate;
  dueDate: CalendarDate | null;
  id: Generated<string>;
  notes: string | null;
  partyName: string;
  reconciliationId: string | null;
  type: LoanType;
  updatedAt: Generated<Timestamp>;
}

export interface ProjectLabors {
  createdAt: Generated<Timestamp>;
  hours: number;
  id: Generated<string>;
  name: string;
  projectId: string;
  rate: number;
  reconciliationId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ProjectMisc {
  amount: number;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  projectId: string;
  reconciliationId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ProjectPayments {
  amount: number;
  createdAt: Generated<Timestamp>;
  date: CalendarDate;
  id: Generated<string>;
  projectId: string;
  reconciliationId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Projects {
  address: string | null;
  budgetUnits: number;
  budgetUnitValue: number;
  client: string;
  createdAt: Generated<Timestamp>;
  endDate: CalendarDate | null;
  humanId: string;
  id: Generated<string>;
  margin: number;
  meters: number | null;
  price: number;
  startDate: CalendarDate | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  visitDate: CalendarDate | null;
}

export interface ProjectSupplies {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  projectId: string;
  quantity: number;
  reconciliationId: string | null;
  unitPrice: number;
  updatedAt: Generated<Timestamp>;
}

export interface Reconciliations {
  amount: number;
  budgetCategoryId: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  gstPaymentId: string | null;
  id: Generated<string>;
  isGst: boolean;
  isPayoff: boolean | null;
  loanId: string | null;
  loanPayoffId: string | null;
  projectId: string | null;
  projectItemId: string | null;
  projectStream: ReconciliationProjectStream | null;
  reconciliationGroup: ReconciliationGroup;
  transactionId: string;
  updatedAt: Generated<Timestamp>;
}

export interface RolePermissions {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  permission: string;
  roleId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Roles {
  createdAt: Generated<Timestamp>;
  description: string | null;
  humanId: string | null;
  id: Generated<string>;
  isBuiltIn: Generated<boolean>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Transactions {
  accountId: string;
  amount: number;
  createdAt: Generated<Timestamp>;
  date: CalendarDate;
  description: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface UserRoles {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  roleId: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verifications {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  _PrismaMigrations: _PrismaMigrations;
  accounts: Accounts;
  budgetCategories: BudgetCategories;
  budgetCategoryAllocations: BudgetCategoryAllocations;
  "drizzle.DrizzleMigrations": DrizzleDrizzleMigrations;
  financialAccounts: FinancialAccounts;
  gstPayments: GstPayments;
  loanPayoffs: LoanPayoffs;
  loans: Loans;
  projectLabors: ProjectLabors;
  projectMisc: ProjectMisc;
  projectPayments: ProjectPayments;
  projects: Projects;
  projectSupplies: ProjectSupplies;
  reconciliations: Reconciliations;
  rolePermissions: RolePermissions;
  roles: Roles;
  sessions: Sessions;
  transactions: Transactions;
  userRoles: UserRoles;
  users: Users;
  verifications: Verifications;
}
