/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ConsolidationBudgetCategory =
  | "consumable"
  | "food"
  | "fuel"
  | "salary"
  | "subscription"
  | "toll"
  | "tool";

export type ConsolidationGroup =
  | "budget"
  | "loan"
  | "project"
  | "refund"
  | "refunded"
  | "tax"
  | "unclassified";

export type ConsolidationProjectStream =
  | "labors"
  | "misc"
  | "payments"
  | "supplies";

export type FinancialAccountBankSyncers = "westpac";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type LoanType = "borrowed" | "lent";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TransactionType = "expense" | "income";

export interface _PrismaMigrations {
  appliedStepsCount: Generated<number>;
  checksum: string;
  finishedAt: Timestamp | null;
  id: string;
  logs: string | null;
  migrationName: string;
  rolledBackAt: Timestamp | null;
  startedAt: Generated<Timestamp>;
}

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Consolidations {
  amount: number;
  budgetCategory: ConsolidationBudgetCategory | null;
  consolidationGroup: ConsolidationGroup;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  isGst: boolean;
  isPayoff: boolean | null;
  loanId: string | null;
  loanPayoffId: string | null;
  projectId: string | null;
  projectItemId: string | null;
  projectStream: ConsolidationProjectStream | null;
  transactionId: string;
  updatedAt: Generated<Timestamp>;
}

export interface DrizzleDrizzleMigrations {
  createdAt: Int8 | null;
  hash: string;
  id: Generated<number>;
}

export interface FinancialAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  syncWithBank: FinancialAccountBankSyncers | null;
  updatedAt: Generated<Timestamp>;
}

export interface LoanPayoffs {
  amount: number;
  consolidationId: string | null;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<string>;
  loanId: string;
  notes: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Loans {
  amount: number;
  consolidationId: string | null;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  dueDate: Timestamp | null;
  id: Generated<string>;
  notes: string | null;
  partyName: string;
  type: LoanType;
  updatedAt: Generated<Timestamp>;
}

export interface ProjectLabors {
  consolidationId: string | null;
  createdAt: Generated<Timestamp>;
  hours: number;
  id: Generated<string>;
  name: string;
  projectId: string;
  rate: number;
  updatedAt: Generated<Timestamp>;
}

export interface ProjectMisc {
  amount: number;
  consolidationId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  projectId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProjectPayments {
  amount: number;
  consolidationId: string | null;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<string>;
  projectId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Projects {
  address: string | null;
  client: string;
  createdAt: Generated<Timestamp>;
  endDate: Timestamp | null;
  humanId: string;
  id: Generated<string>;
  margin: number;
  meters: number | null;
  price: number;
  startDate: Timestamp | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  visitDate: Timestamp | null;
}

export interface ProjectSupplies {
  consolidationId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  projectId: string;
  quantity: number;
  unitPrice: number;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Transactions {
  accountId: string;
  amount: number;
  createdAt: Generated<Timestamp>;
  date: Timestamp;
  description: string;
  id: Generated<string>;
  type: TransactionType;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verifications {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  _PrismaMigrations: _PrismaMigrations;
  accounts: Accounts;
  consolidations: Consolidations;
  "drizzle.DrizzleMigrations": DrizzleDrizzleMigrations;
  financialAccounts: FinancialAccounts;
  loanPayoffs: LoanPayoffs;
  loans: Loans;
  projectLabors: ProjectLabors;
  projectMisc: ProjectMisc;
  projectPayments: ProjectPayments;
  projects: Projects;
  projectSupplies: ProjectSupplies;
  sessions: Sessions;
  transactions: Transactions;
  users: Users;
  verifications: Verifications;
}
