import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "next-themes";
import { getLocale } from "next-intl/server";
import { Providers } from "./_components/providers";
import { getDir } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

export const dynamic = "force-dynamic"; // no full-route cache
export const revalidate = 0; // no ISR
export const fetchCache = "default-no-store"; // all fetch() => no-store by default

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const locale = await getLocale();
    const dir = getDir(locale);

    return (
        <html lang={locale} dir={dir} suppressHydrationWarning>
            <body
                dir={dir}
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <TRPCReactProvider>
                    <NextIntlClientProvider>
                        <ThemeProvider
                            attribute="class"
                            enableSystem
                            defaultTheme="system"
                            disableTransitionOnChange
                        >
                            <Providers>
                                <Toaster />
                                {children}
                            </Providers>
                        </ThemeProvider>
                    </NextIntlClientProvider>
                </TRPCReactProvider>
            </body>
        </html>
    );
};

export default RootLayout;
