/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardAccessControlRouteImport } from './routes/_dashboard/access-control'
import { Route as DashboardReconciliationsIndexRouteImport } from './routes/_dashboard/reconciliations/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard/projects/index'
import { Route as DashboardLoansIndexRouteImport } from './routes/_dashboard/loans/index'
import { Route as DashboardFinancialAccountsIndexRouteImport } from './routes/_dashboard/financial-accounts/index'
import { Route as DashboardBudgetsIndexRouteImport } from './routes/_dashboard/budgets/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardToolsPriceCalculatorRouteImport } from './routes/_dashboard/tools/price-calculator'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/_dashboard/projects/$projectId'
import { Route as DashboardPayrollSettingsRouteImport } from './routes/_dashboard/payroll/settings'
import { Route as DashboardPayrollPaySchedulesRouteImport } from './routes/_dashboard/payroll/pay-schedules'
import { Route as DashboardPayrollEmployeesRouteImport } from './routes/_dashboard/payroll/employees'
import { Route as DashboardLoansLoanIdRouteImport } from './routes/_dashboard/loans/$loanId'
import { Route as DashboardGstPendingRouteImport } from './routes/_dashboard/gst/pending'
import { Route as DashboardGstPaymentsRouteImport } from './routes/_dashboard/gst/payments'
import { Route as DashboardFinancialAccountsAccountIdRouteImport } from './routes/_dashboard/financial-accounts/$accountId'
import { Route as DashboardBudgetsBudgetCategoryIdRouteImport } from './routes/_dashboard/budgets/$budgetCategoryId'
import { Route as DashboardPayrollPayRunsIndexRouteImport } from './routes/_dashboard/payroll/pay-runs/index'
import { Route as DashboardPayrollPayRunsIdRouteImport } from './routes/_dashboard/payroll/pay-runs/$id'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccessControlRoute = DashboardAccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReconciliationsIndexRoute =
  DashboardReconciliationsIndexRouteImport.update({
    id: '/reconciliations/',
    path: '/reconciliations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLoansIndexRoute = DashboardLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinancialAccountsIndexRoute =
  DashboardFinancialAccountsIndexRouteImport.update({
    id: '/financial-accounts/',
    path: '/financial-accounts/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBudgetsIndexRoute = DashboardBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardToolsPriceCalculatorRoute =
  DashboardToolsPriceCalculatorRouteImport.update({
    id: '/tools/price-calculator',
    path: '/tools/price-calculator',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPayrollSettingsRoute =
  DashboardPayrollSettingsRouteImport.update({
    id: '/payroll/settings',
    path: '/payroll/settings',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPayrollPaySchedulesRoute =
  DashboardPayrollPaySchedulesRouteImport.update({
    id: '/payroll/pay-schedules',
    path: '/payroll/pay-schedules',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPayrollEmployeesRoute =
  DashboardPayrollEmployeesRouteImport.update({
    id: '/payroll/employees',
    path: '/payroll/employees',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLoansLoanIdRoute = DashboardLoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGstPendingRoute = DashboardGstPendingRouteImport.update({
  id: '/gst/pending',
  path: '/gst/pending',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGstPaymentsRoute = DashboardGstPaymentsRouteImport.update({
  id: '/gst/payments',
  path: '/gst/payments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinancialAccountsAccountIdRoute =
  DashboardFinancialAccountsAccountIdRouteImport.update({
    id: '/financial-accounts/$accountId',
    path: '/financial-accounts/$accountId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBudgetsBudgetCategoryIdRoute =
  DashboardBudgetsBudgetCategoryIdRouteImport.update({
    id: '/budgets/$budgetCategoryId',
    path: '/budgets/$budgetCategoryId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPayrollPayRunsIndexRoute =
  DashboardPayrollPayRunsIndexRouteImport.update({
    id: '/payroll/pay-runs/',
    path: '/payroll/pay-runs/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPayrollPayRunsIdRoute =
  DashboardPayrollPayRunsIdRouteImport.update({
    id: '/payroll/pay-runs/$id',
    path: '/payroll/pay-runs/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/access-control': typeof DashboardAccessControlRoute
  '/users': typeof DashboardUsersRoute
  '/login': typeof GuestLoginRoute
  '/budgets/$budgetCategoryId': typeof DashboardBudgetsBudgetCategoryIdRoute
  '/financial-accounts/$accountId': typeof DashboardFinancialAccountsAccountIdRoute
  '/gst/payments': typeof DashboardGstPaymentsRoute
  '/gst/pending': typeof DashboardGstPendingRoute
  '/loans/$loanId': typeof DashboardLoansLoanIdRoute
  '/payroll/employees': typeof DashboardPayrollEmployeesRoute
  '/payroll/pay-schedules': typeof DashboardPayrollPaySchedulesRoute
  '/payroll/settings': typeof DashboardPayrollSettingsRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/tools/price-calculator': typeof DashboardToolsPriceCalculatorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/budgets/': typeof DashboardBudgetsIndexRoute
  '/financial-accounts/': typeof DashboardFinancialAccountsIndexRoute
  '/loans/': typeof DashboardLoansIndexRoute
  '/projects/': typeof DashboardProjectsIndexRoute
  '/reconciliations/': typeof DashboardReconciliationsIndexRoute
  '/payroll/pay-runs/$id': typeof DashboardPayrollPayRunsIdRoute
  '/payroll/pay-runs/': typeof DashboardPayrollPayRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/access-control': typeof DashboardAccessControlRoute
  '/users': typeof DashboardUsersRoute
  '/login': typeof GuestLoginRoute
  '/budgets/$budgetCategoryId': typeof DashboardBudgetsBudgetCategoryIdRoute
  '/financial-accounts/$accountId': typeof DashboardFinancialAccountsAccountIdRoute
  '/gst/payments': typeof DashboardGstPaymentsRoute
  '/gst/pending': typeof DashboardGstPendingRoute
  '/loans/$loanId': typeof DashboardLoansLoanIdRoute
  '/payroll/employees': typeof DashboardPayrollEmployeesRoute
  '/payroll/pay-schedules': typeof DashboardPayrollPaySchedulesRoute
  '/payroll/settings': typeof DashboardPayrollSettingsRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/tools/price-calculator': typeof DashboardToolsPriceCalculatorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/budgets': typeof DashboardBudgetsIndexRoute
  '/financial-accounts': typeof DashboardFinancialAccountsIndexRoute
  '/loans': typeof DashboardLoansIndexRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/reconciliations': typeof DashboardReconciliationsIndexRoute
  '/payroll/pay-runs/$id': typeof DashboardPayrollPayRunsIdRoute
  '/payroll/pay-runs': typeof DashboardPayrollPayRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_dashboard/access-control': typeof DashboardAccessControlRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/budgets/$budgetCategoryId': typeof DashboardBudgetsBudgetCategoryIdRoute
  '/_dashboard/financial-accounts/$accountId': typeof DashboardFinancialAccountsAccountIdRoute
  '/_dashboard/gst/payments': typeof DashboardGstPaymentsRoute
  '/_dashboard/gst/pending': typeof DashboardGstPendingRoute
  '/_dashboard/loans/$loanId': typeof DashboardLoansLoanIdRoute
  '/_dashboard/payroll/employees': typeof DashboardPayrollEmployeesRoute
  '/_dashboard/payroll/pay-schedules': typeof DashboardPayrollPaySchedulesRoute
  '/_dashboard/payroll/settings': typeof DashboardPayrollSettingsRoute
  '/_dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/_dashboard/tools/price-calculator': typeof DashboardToolsPriceCalculatorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_dashboard/budgets/': typeof DashboardBudgetsIndexRoute
  '/_dashboard/financial-accounts/': typeof DashboardFinancialAccountsIndexRoute
  '/_dashboard/loans/': typeof DashboardLoansIndexRoute
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/reconciliations/': typeof DashboardReconciliationsIndexRoute
  '/_dashboard/payroll/pay-runs/$id': typeof DashboardPayrollPayRunsIdRoute
  '/_dashboard/payroll/pay-runs/': typeof DashboardPayrollPayRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-control'
    | '/users'
    | '/login'
    | '/budgets/$budgetCategoryId'
    | '/financial-accounts/$accountId'
    | '/gst/payments'
    | '/gst/pending'
    | '/loans/$loanId'
    | '/payroll/employees'
    | '/payroll/pay-schedules'
    | '/payroll/settings'
    | '/projects/$projectId'
    | '/tools/price-calculator'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/budgets/'
    | '/financial-accounts/'
    | '/loans/'
    | '/projects/'
    | '/reconciliations/'
    | '/payroll/pay-runs/$id'
    | '/payroll/pay-runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-control'
    | '/users'
    | '/login'
    | '/budgets/$budgetCategoryId'
    | '/financial-accounts/$accountId'
    | '/gst/payments'
    | '/gst/pending'
    | '/loans/$loanId'
    | '/payroll/employees'
    | '/payroll/pay-schedules'
    | '/payroll/settings'
    | '/projects/$projectId'
    | '/tools/price-calculator'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/budgets'
    | '/financial-accounts'
    | '/loans'
    | '/projects'
    | '/reconciliations'
    | '/payroll/pay-runs/$id'
    | '/payroll/pay-runs'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_guest'
    | '/_dashboard/access-control'
    | '/_dashboard/users'
    | '/_guest/login'
    | '/_dashboard/'
    | '/_dashboard/budgets/$budgetCategoryId'
    | '/_dashboard/financial-accounts/$accountId'
    | '/_dashboard/gst/payments'
    | '/_dashboard/gst/pending'
    | '/_dashboard/loans/$loanId'
    | '/_dashboard/payroll/employees'
    | '/_dashboard/payroll/pay-schedules'
    | '/_dashboard/payroll/settings'
    | '/_dashboard/projects/$projectId'
    | '/_dashboard/tools/price-calculator'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_dashboard/budgets/'
    | '/_dashboard/financial-accounts/'
    | '/_dashboard/loans/'
    | '/_dashboard/projects/'
    | '/_dashboard/reconciliations/'
    | '/_dashboard/payroll/pay-runs/$id'
    | '/_dashboard/payroll/pay-runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/access-control': {
      id: '/_dashboard/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof DashboardAccessControlRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/reconciliations/': {
      id: '/_dashboard/reconciliations/'
      path: '/reconciliations'
      fullPath: '/reconciliations/'
      preLoaderRoute: typeof DashboardReconciliationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/loans/': {
      id: '/_dashboard/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof DashboardLoansIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/financial-accounts/': {
      id: '/_dashboard/financial-accounts/'
      path: '/financial-accounts'
      fullPath: '/financial-accounts/'
      preLoaderRoute: typeof DashboardFinancialAccountsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/budgets/': {
      id: '/_dashboard/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof DashboardBudgetsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/tools/price-calculator': {
      id: '/_dashboard/tools/price-calculator'
      path: '/tools/price-calculator'
      fullPath: '/tools/price-calculator'
      preLoaderRoute: typeof DashboardToolsPriceCalculatorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/projects/$projectId': {
      id: '/_dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/payroll/settings': {
      id: '/_dashboard/payroll/settings'
      path: '/payroll/settings'
      fullPath: '/payroll/settings'
      preLoaderRoute: typeof DashboardPayrollSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/payroll/pay-schedules': {
      id: '/_dashboard/payroll/pay-schedules'
      path: '/payroll/pay-schedules'
      fullPath: '/payroll/pay-schedules'
      preLoaderRoute: typeof DashboardPayrollPaySchedulesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/payroll/employees': {
      id: '/_dashboard/payroll/employees'
      path: '/payroll/employees'
      fullPath: '/payroll/employees'
      preLoaderRoute: typeof DashboardPayrollEmployeesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/loans/$loanId': {
      id: '/_dashboard/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof DashboardLoansLoanIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/gst/pending': {
      id: '/_dashboard/gst/pending'
      path: '/gst/pending'
      fullPath: '/gst/pending'
      preLoaderRoute: typeof DashboardGstPendingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/gst/payments': {
      id: '/_dashboard/gst/payments'
      path: '/gst/payments'
      fullPath: '/gst/payments'
      preLoaderRoute: typeof DashboardGstPaymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/financial-accounts/$accountId': {
      id: '/_dashboard/financial-accounts/$accountId'
      path: '/financial-accounts/$accountId'
      fullPath: '/financial-accounts/$accountId'
      preLoaderRoute: typeof DashboardFinancialAccountsAccountIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/budgets/$budgetCategoryId': {
      id: '/_dashboard/budgets/$budgetCategoryId'
      path: '/budgets/$budgetCategoryId'
      fullPath: '/budgets/$budgetCategoryId'
      preLoaderRoute: typeof DashboardBudgetsBudgetCategoryIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/payroll/pay-runs/': {
      id: '/_dashboard/payroll/pay-runs/'
      path: '/payroll/pay-runs'
      fullPath: '/payroll/pay-runs/'
      preLoaderRoute: typeof DashboardPayrollPayRunsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/payroll/pay-runs/$id': {
      id: '/_dashboard/payroll/pay-runs/$id'
      path: '/payroll/pay-runs/$id'
      fullPath: '/payroll/pay-runs/$id'
      preLoaderRoute: typeof DashboardPayrollPayRunsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAccessControlRoute: typeof DashboardAccessControlRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBudgetsBudgetCategoryIdRoute: typeof DashboardBudgetsBudgetCategoryIdRoute
  DashboardFinancialAccountsAccountIdRoute: typeof DashboardFinancialAccountsAccountIdRoute
  DashboardGstPaymentsRoute: typeof DashboardGstPaymentsRoute
  DashboardGstPendingRoute: typeof DashboardGstPendingRoute
  DashboardLoansLoanIdRoute: typeof DashboardLoansLoanIdRoute
  DashboardPayrollEmployeesRoute: typeof DashboardPayrollEmployeesRoute
  DashboardPayrollPaySchedulesRoute: typeof DashboardPayrollPaySchedulesRoute
  DashboardPayrollSettingsRoute: typeof DashboardPayrollSettingsRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardToolsPriceCalculatorRoute: typeof DashboardToolsPriceCalculatorRoute
  DashboardBudgetsIndexRoute: typeof DashboardBudgetsIndexRoute
  DashboardFinancialAccountsIndexRoute: typeof DashboardFinancialAccountsIndexRoute
  DashboardLoansIndexRoute: typeof DashboardLoansIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardReconciliationsIndexRoute: typeof DashboardReconciliationsIndexRoute
  DashboardPayrollPayRunsIdRoute: typeof DashboardPayrollPayRunsIdRoute
  DashboardPayrollPayRunsIndexRoute: typeof DashboardPayrollPayRunsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccessControlRoute: DashboardAccessControlRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBudgetsBudgetCategoryIdRoute: DashboardBudgetsBudgetCategoryIdRoute,
  DashboardFinancialAccountsAccountIdRoute:
    DashboardFinancialAccountsAccountIdRoute,
  DashboardGstPaymentsRoute: DashboardGstPaymentsRoute,
  DashboardGstPendingRoute: DashboardGstPendingRoute,
  DashboardLoansLoanIdRoute: DashboardLoansLoanIdRoute,
  DashboardPayrollEmployeesRoute: DashboardPayrollEmployeesRoute,
  DashboardPayrollPaySchedulesRoute: DashboardPayrollPaySchedulesRoute,
  DashboardPayrollSettingsRoute: DashboardPayrollSettingsRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardToolsPriceCalculatorRoute: DashboardToolsPriceCalculatorRoute,
  DashboardBudgetsIndexRoute: DashboardBudgetsIndexRoute,
  DashboardFinancialAccountsIndexRoute: DashboardFinancialAccountsIndexRoute,
  DashboardLoansIndexRoute: DashboardLoansIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardReconciliationsIndexRoute: DashboardReconciliationsIndexRoute,
  DashboardPayrollPayRunsIdRoute: DashboardPayrollPayRunsIdRoute,
  DashboardPayrollPayRunsIndexRoute: DashboardPayrollPayRunsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
