#!/usr/bin/env sh

# Get the current branch name
branch_name="$(git rev-parse --abbrev-ref HEAD)"

# Define a regular expression for valid branch names
valid_branch_regex='^((feat|fix|build|chore|ci|docs|perf|refactor|revert|style|test)/[a-zA-Z0-9\-]+)$'

# List of exception branch names
exception_branches="develop prerelease main"

# Error message for an invalid branch name
message="
    Error: Your branch name ($branch_name) is invalid.

    Branch names must follow the specified pattern:
        $valid_branch_regex

    Valid examples:
    - feat/new-feature
    - fix/bug-fix-123

    Invalid examples:
    - my-feature (missing prefix)
    - feat/important-feature! (invalid characters)
    - fix/enhancement_feature (contains underscore '_')"

# Check if the branch name matches the regex or is in the exception list
valid_branch=false
for exception_branch in $exception_branches; do
    if [ "$branch_name" = "$exception_branch" ]; then
        valid_branch=true
        break
    fi
done

if [ "$valid_branch" != "true" ] && ! echo "$branch_name" | grep -Eq "$valid_branch_regex"; then
    echo "$message"
    exit 1
fi

